services:

  postgres:
    image: postgres:17.0
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./script:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: NatsumiChan
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgres:5432
    networks:
      - my-network
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./src/main/resources/templates:/src/main/resources/templates  # Монтирование папки templates
      - ./src/main/resources/static:/src/main/resources/static  # Монтирование папки static
    networks:
      - my-network
    depends_on:
      - kv
  kv:
    image: kv:latest
    build:
      context: .
      args:
        DOCKER_BUILDKIT: 1
    restart: "no"
    ports:
      - "8080:8080"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/ || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    depends_on:
      - postgres
    networks:
      - my-network
volumes:
  postgres_data:
networks:
  my-network:
