apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f C:\Users\nazar\OneDrive\Desktop\kvv\docker-compose.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: kv
  name: kv
spec:
  containers:
    - image: natsumichan/kv:latest
      livenessProbe:
        exec:
          command:
            - curl --fail http://localhost:8080/ || exit 1
        failureThreshold: 5
        initialDelaySeconds: 30
        periodSeconds: 30
        timeoutSeconds: 5
      name: kv
      ports:
        - containerPort: 8080
          protocol: TCP
  restartPolicy: Always
